// Snapshot of generated/instruments/Scratch FMX Tines.sunsynth; no runtime dependency on the original file.
// SHA-256: e1a2552e6f62ba161b36c05f7c3c146171a9d820d37fd48057559906618da6a2
export const FMX_TINES = {
  name: "Scratch FMX Tines",
  type: "FMX",
  finetune: 0,
  controllers: [
    {"index":0,"name":"Volume","value":11200},
    {"index":1,"name":"Panning","value":128},
    {"index":2,"name":"Sample rate","value":6},
    {"index":3,"name":"Polyphony","value":10},
    {"index":4,"name":"Channels","value":1},
    {"index":5,"name":"Input -> Operator #","value":0},
    {"index":6,"name":"Input -> Custom waveform","value":0},
    {"index":7,"name":"ADSR smooth transitions","value":1},
    {"index":8,"name":"Noise filter (32768 - OFF)","value":32768},
    {"index":9,"name":"1 Volume","value":32768},
    {"index":10,"name":"2 Volume","value":14200},
    {"index":11,"name":"3 Volume","value":15500},
    {"index":12,"name":"4 Volume","value":14000},
    {"index":13,"name":"5 Volume","value":12000},
    {"index":14,"name":"1 Attack","value":1},
    {"index":15,"name":"2 Attack","value":1},
    {"index":16,"name":"3 Attack","value":1},
    {"index":17,"name":"4 Attack","value":1},
    {"index":18,"name":"5 Attack","value":1},
    {"index":19,"name":"1 Decay","value":1},
    {"index":20,"name":"2 Decay","value":2600},
    {"index":21,"name":"3 Decay","value":6400},
    {"index":22,"name":"4 Decay","value":5000},
    {"index":23,"name":"5 Decay","value":4200},
    {"index":24,"name":"1 Sustain level","value":0},
    {"index":25,"name":"2 Sustain level","value":0},
    {"index":26,"name":"3 Sustain level","value":0},
    {"index":27,"name":"4 Sustain level","value":0},
    {"index":28,"name":"5 Sustain level","value":0},
    {"index":29,"name":"1 Release","value":140},
    {"index":30,"name":"2 Release","value":120},
    {"index":31,"name":"3 Release","value":210},
    {"index":32,"name":"4 Release","value":190},
    {"index":33,"name":"5 Release","value":180},
    {"index":34,"name":"1 Attack curve","value":3},
    {"index":35,"name":"2 Attack curve","value":3},
    {"index":36,"name":"3 Attack curve","value":3},
    {"index":37,"name":"4 Attack curve","value":3},
    {"index":38,"name":"5 Attack curve","value":3},
    {"index":39,"name":"1 Decay curve","value":2},
    {"index":40,"name":"2 Decay curve","value":2},
    {"index":41,"name":"3 Decay curve","value":2},
    {"index":42,"name":"4 Decay curve","value":2},
    {"index":43,"name":"5 Decay curve","value":2},
    {"index":44,"name":"1 Release curve","value":1},
    {"index":45,"name":"2 Release curve","value":1},
    {"index":46,"name":"3 Release curve","value":1},
    {"index":47,"name":"4 Release curve","value":1},
    {"index":48,"name":"5 Release curve","value":1},
    {"index":49,"name":"1 Sustain","value":0},
    {"index":50,"name":"2 Sustain","value":0},
    {"index":51,"name":"3 Sustain","value":0},
    {"index":52,"name":"4 Sustain","value":0},
    {"index":53,"name":"5 Sustain","value":0},
    {"index":54,"name":"1 Sustain pedal","value":0},
    {"index":55,"name":"2 Sustain pedal","value":0},
    {"index":56,"name":"3 Sustain pedal","value":0},
    {"index":57,"name":"4 Sustain pedal","value":0},
    {"index":58,"name":"5 Sustain pedal","value":0},
    {"index":59,"name":"1 Envelope scaling per key","value":128},
    {"index":60,"name":"2 Envelope scaling per key","value":112},
    {"index":61,"name":"3 Envelope scaling per key","value":128},
    {"index":62,"name":"4 Envelope scaling per key","value":128},
    {"index":63,"name":"5 Envelope scaling per key","value":128},
    {"index":64,"name":"1 Volume scaling per key","value":128},
    {"index":65,"name":"2 Volume scaling per key","value":192},
    {"index":66,"name":"3 Volume scaling per key","value":128},
    {"index":67,"name":"4 Volume scaling per key","value":128},
    {"index":68,"name":"5 Volume scaling per key","value":128},
    {"index":69,"name":"1 Velocity sensitivity","value":192},
    {"index":70,"name":"2 Velocity sensitivity","value":192},
    {"index":71,"name":"3 Velocity sensitivity","value":192},
    {"index":72,"name":"4 Velocity sensitivity","value":192},
    {"index":73,"name":"5 Velocity sensitivity","value":192},
    {"index":74,"name":"1 Waveform","value":6},
    {"index":75,"name":"2 Waveform","value":6},
    {"index":76,"name":"3 Waveform","value":6},
    {"index":77,"name":"4 Waveform","value":6},
    {"index":78,"name":"5 Waveform","value":6},
    {"index":79,"name":"1 Noise","value":0},
    {"index":80,"name":"2 Noise","value":0},
    {"index":81,"name":"3 Noise","value":0},
    {"index":82,"name":"4 Noise","value":80},
    {"index":83,"name":"5 Noise","value":180},
    {"index":84,"name":"1 Phase","value":0},
    {"index":85,"name":"2 Phase","value":0},
    {"index":86,"name":"3 Phase","value":0},
    {"index":87,"name":"4 Phase","value":0},
    {"index":88,"name":"5 Phase","value":0},
    {"index":89,"name":"1 Freq multiply","value":1000},
    {"index":90,"name":"2 Freq multiply","value":12000},
    {"index":91,"name":"3 Freq multiply","value":1000},
    {"index":92,"name":"4 Freq multiply","value":995},
    {"index":93,"name":"5 Freq multiply","value":1005},
    {"index":94,"name":"1 Constant pitch","value":8192},
    {"index":95,"name":"2 Constant pitch","value":8192},
    {"index":96,"name":"3 Constant pitch","value":8192},
    {"index":97,"name":"4 Constant pitch","value":8192},
    {"index":98,"name":"5 Constant pitch","value":8192},
    {"index":99,"name":"1 Self-modulation","value":0},
    {"index":100,"name":"2 Self-modulation","value":0},
    {"index":101,"name":"3 Self-modulation","value":0},
    {"index":102,"name":"4 Self-modulation","value":700},
    {"index":103,"name":"5 Self-modulation","value":520},
    {"index":104,"name":"1 Feedback","value":0},
    {"index":105,"name":"2 Feedback","value":0},
    {"index":106,"name":"3 Feedback","value":0},
    {"index":107,"name":"4 Feedback","value":0},
    {"index":108,"name":"5 Feedback","value":0},
    {"index":109,"name":"1 Modulation type","value":0},
    {"index":110,"name":"2 Modulation type","value":0},
    {"index":111,"name":"3 Modulation type","value":0},
    {"index":112,"name":"4 Modulation type","value":0},
    {"index":113,"name":"5 Modulation type","value":0},
    {"index":114,"name":"1 Output mode","value":0},
    {"index":115,"name":"2 Output mode","value":8},
    {"index":116,"name":"3 Output mode","value":1},
    {"index":117,"name":"4 Output mode","value":1},
    {"index":118,"name":"Envelope gain","value":1000},
  ],
};
