// Call signatures sent to the dedicated worker for argument validation.
export const ENGINE_API = {
  "sv_get_sample_rate": {"args": [], "result": "number", "lock": false},
  "sv_open_slot": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_close_slot": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_load_from_memory": {"args": [["slot", "number"], ["byte_array", "Uint8Array"]], "result": "number", "lock": false},
  "sv_save_to_memory": {"args": [["slot", "number"]], "result": "Uint8Array | null", "lock": false},
  "sv_play": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_play_from_beginning": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_stop": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_pause": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_resume": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_sync_resume": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_set_autostop": {"args": [["slot", "number"], ["autostop", "number"]], "result": "number", "lock": false},
  "sv_get_autostop": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_end_of_song": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_rewind": {"args": [["slot", "number"], ["line_num", "number"]], "result": "number", "lock": false},
  "sv_volume": {"args": [["slot", "number"], ["vol", "number"]], "result": "number", "lock": false},
  "sv_set_event_t": {"args": [["slot", "number"], ["set", "number"], ["t", "number"]], "result": "number", "lock": false},
  "sv_send_event": {"args": [["slot", "number"], ["track", "number"], ["note", "number"], ["vel", "number"], ["module", "number"], ["ctl", "number"], ["ctl_val", "number"]], "result": "number", "lock": false},
  "sv_get_current_line": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_get_current_line2": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_get_current_signal_level": {"args": [["slot", "number"], ["channel", "number"]], "result": "number", "lock": false},
  "sv_get_song_name": {"args": [["slot", "number"]], "result": "string", "lock": false},
  "sv_set_song_name": {"args": [["slot", "number"], ["name", "string"]], "result": "number", "lock": false},
  "sv_get_base_version": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_get_song_bpm": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_get_song_tpl": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_get_song_length_frames": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_get_song_length_lines": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_get_time_map": {"args": [["slot", "number"], ["start_line", "number"], ["len", "number"], ["flags", "number"]], "result": "BufferResult<Uint32Array>", "lock": false},
  "sv_new_module": {"args": [["slot", "number"], ["type", "string"], ["name", "string"], ["x", "number"], ["y", "number"], ["z", "number"]], "result": "number", "lock": true},
  "sv_remove_module": {"args": [["slot", "number"], ["mod_num", "number"]], "result": "number", "lock": true},
  "sv_connect_module": {"args": [["slot", "number"], ["source", "number"], ["destination", "number"]], "result": "number", "lock": true},
  "sv_disconnect_module": {"args": [["slot", "number"], ["source", "number"], ["destination", "number"]], "result": "number", "lock": true},
  "sv_load_module_from_memory": {"args": [["slot", "number"], ["byte_array", "Uint8Array"], ["x", "number"], ["y", "number"], ["z", "number"]], "result": "number", "lock": false},
  "sv_sampler_load_from_memory": {"args": [["slot", "number"], ["mod_num", "number"], ["byte_array", "Uint8Array"], ["sample_slot", "number"]], "result": "number", "lock": false},
  "sv_sampler_par": {"args": [["slot", "number"], ["mod_num", "number"], ["sample_slot", "number"], ["par", "number"], ["par_val", "number"], ["set", "number"]], "result": "number", "lock": false},
  "sv_metamodule_load_from_memory": {"args": [["slot", "number"], ["mod_num", "number"], ["byte_array", "Uint8Array"]], "result": "number", "lock": false},
  "sv_vplayer_load_from_memory": {"args": [["slot", "number"], ["mod_num", "number"], ["byte_array", "Uint8Array"]], "result": "number", "lock": false},
  "sv_get_number_of_modules": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_find_module": {"args": [["slot", "number"], ["name", "string"]], "result": "number", "lock": false},
  "sv_get_module_flags": {"args": [["slot", "number"], ["mod_num", "number"]], "result": "number", "lock": false},
  "sv_get_module_inputs": {"args": [["slot", "number"], ["mod_num", "number"]], "result": "Int32Array | null", "lock": false},
  "sv_get_module_outputs": {"args": [["slot", "number"], ["mod_num", "number"]], "result": "Int32Array | null", "lock": false},
  "sv_get_module_type": {"args": [["slot", "number"], ["mod_num", "number"]], "result": "string", "lock": false},
  "sv_get_module_name": {"args": [["slot", "number"], ["mod_num", "number"]], "result": "string", "lock": false},
  "sv_set_module_name": {"args": [["slot", "number"], ["mod_num", "number"], ["name", "string"]], "result": "number", "lock": false},
  "sv_get_module_xy": {"args": [["slot", "number"], ["mod_num", "number"]], "result": "number", "lock": false},
  "sv_set_module_xy": {"args": [["slot", "number"], ["mod_num", "number"], ["x", "number"], ["y", "number"]], "result": "number", "lock": false},
  "sv_get_module_color": {"args": [["slot", "number"], ["mod_num", "number"]], "result": "number", "lock": false},
  "sv_set_module_color": {"args": [["slot", "number"], ["mod_num", "number"], ["color", "number"]], "result": "number", "lock": false},
  "sv_get_module_finetune": {"args": [["slot", "number"], ["mod_num", "number"]], "result": "number", "lock": false},
  "sv_set_module_finetune": {"args": [["slot", "number"], ["mod_num", "number"], ["finetune", "number"]], "result": "number", "lock": false},
  "sv_set_module_relnote": {"args": [["slot", "number"], ["mod_num", "number"], ["relnote", "number"]], "result": "number", "lock": false},
  "sv_get_module_scope2": {"args": [["slot", "number"], ["mod_num", "number"], ["channel", "number"], ["samples_to_read", "number"]], "result": "BufferResult<Int16Array>", "lock": false},
  "sv_module_curve": {"args": [["slot", "number"], ["mod_num", "number"], ["curve_num", "number"], ["buf_float32", "Float32Array"], ["len", "number"], ["w", "number"]], "result": "BufferResult<Float32Array>", "lock": false},
  "sv_get_number_of_module_ctls": {"args": [["slot", "number"], ["mod_num", "number"]], "result": "number", "lock": false},
  "sv_get_module_ctl_name": {"args": [["slot", "number"], ["mod_num", "number"], ["ctl_num", "number"]], "result": "string", "lock": false},
  "sv_get_module_ctl_value": {"args": [["slot", "number"], ["mod_num", "number"], ["ctl_num", "number"], ["scaled", "number"]], "result": "number", "lock": false},
  "sv_set_module_ctl_value": {"args": [["slot", "number"], ["mod_num", "number"], ["ctl_num", "number"], ["val", "number"], ["scaled", "number"]], "result": "number", "lock": false},
  "sv_get_module_ctl_min": {"args": [["slot", "number"], ["mod_num", "number"], ["ctl_num", "number"], ["scaled", "number"]], "result": "number", "lock": false},
  "sv_get_module_ctl_max": {"args": [["slot", "number"], ["mod_num", "number"], ["ctl_num", "number"], ["scaled", "number"]], "result": "number", "lock": false},
  "sv_get_module_ctl_offset": {"args": [["slot", "number"], ["mod_num", "number"], ["ctl_num", "number"]], "result": "number", "lock": false},
  "sv_get_module_ctl_type": {"args": [["slot", "number"], ["mod_num", "number"], ["ctl_num", "number"]], "result": "number", "lock": false},
  "sv_get_module_ctl_group": {"args": [["slot", "number"], ["mod_num", "number"], ["ctl_num", "number"]], "result": "number", "lock": false},
  "sv_new_pattern": {"args": [["slot", "number"], ["clone", "number"], ["x", "number"], ["y", "number"], ["tracks", "number"], ["lines", "number"], ["icon_seed", "number"], ["name", "string"]], "result": "number", "lock": true},
  "sv_remove_pattern": {"args": [["slot", "number"], ["pat_num", "number"]], "result": "number", "lock": true},
  "sv_get_number_of_patterns": {"args": [["slot", "number"]], "result": "number", "lock": false},
  "sv_find_pattern": {"args": [["slot", "number"], ["name", "string"]], "result": "number", "lock": false},
  "sv_get_pattern_x": {"args": [["slot", "number"], ["pat_num", "number"]], "result": "number", "lock": false},
  "sv_get_pattern_y": {"args": [["slot", "number"], ["pat_num", "number"]], "result": "number", "lock": false},
  "sv_set_pattern_xy": {"args": [["slot", "number"], ["pat_num", "number"], ["x", "number"], ["y", "number"]], "result": "number", "lock": true},
  "sv_get_pattern_tracks": {"args": [["slot", "number"], ["pat_num", "number"]], "result": "number", "lock": false},
  "sv_get_pattern_lines": {"args": [["slot", "number"], ["pat_num", "number"]], "result": "number", "lock": false},
  "sv_set_pattern_size": {"args": [["slot", "number"], ["pat_num", "number"], ["tracks", "number"], ["lines", "number"]], "result": "number", "lock": true},
  "sv_get_pattern_name": {"args": [["slot", "number"], ["pat_num", "number"]], "result": "string", "lock": false},
  "sv_set_pattern_name": {"args": [["slot", "number"], ["pat_num", "number"], ["name", "string"]], "result": "number", "lock": true},
  "sv_get_pattern_data": {"args": [["slot", "number"], ["pat_num", "number"]], "result": "Uint8Array | null", "lock": false},
  "sv_set_pattern_event": {"args": [["slot", "number"], ["pat_num", "number"], ["track", "number"], ["line", "number"], ["nn", "number"], ["vv", "number"], ["mm", "number"], ["ccee", "number"], ["xxyy", "number"]], "result": "number", "lock": false},
  "sv_get_pattern_event": {"args": [["slot", "number"], ["pat_num", "number"], ["track", "number"], ["line", "number"], ["column", "number"]], "result": "number", "lock": false},
  "sv_pattern_mute": {"args": [["slot", "number"], ["pat_num", "number"], ["mute", "number"]], "result": "number", "lock": true},
  "sv_get_ticks": {"args": [], "result": "number", "lock": false},
  "sv_get_ticks_per_second": {"args": [], "result": "number", "lock": false},
  "sv_get_log": {"args": [["size", "number"]], "result": "string", "lock": false},
};
